# Generated by Django 4.2.3 on 2023-07-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Электронная почта')),
                ('username', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Cотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
