# Generated by Django 4.2.3 on 2023-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Город'),
        ),
    ]
