# Generated by Django 4.2.3 on 2023-07-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
