# Generated by Django 4.2.3 on 2023-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
    ]
