# Generated by Django 4.2.3 on 2023-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_purchase_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='old',
            field=models.BooleanField(default=False, verbose_name='Выполненный заказ'),
        ),
    ]
