# Generated by Django 4.2.3 on 2023-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_remove_wishes_product_wishes_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
