# Generated by Django 4.2.3 on 2023-07-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_remove_wishes_content_type_remove_wishes_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='product',
        ),
    ]
