# Generated by Django 4.2.3 on 2023-07-29 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_sweatshirt_clothes_ptr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishes', '0007_alter_wishes_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishes',
            unique_together={('user', 'product')},
        ),
    ]
