# Generated by Django 4.2.3 on 2023-07-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoody',
            options={'verbose_name': 'Худи', 'verbose_name_plural': 'Худи'},
        ),
    ]
