# Generated by Django 4.2.3 on 2023-07-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_hoody_polymorphic_ctype_sweatshirt_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoody',
            name='color',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='material',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='material',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='material',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
    ]
