# Generated by Django 4.2.3 on 2023-07-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_hoody_color_remove_hoody_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoody',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='price',
        ),
        migrations.AddField(
            model_name='hoody',
            name='color',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hoody',
            name='material',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hoody',
            name='size',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sweatshirt',
            name='color',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sweatshirt',
            name='material',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sweatshirt',
            name='size',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='color',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='material',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='size',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
