# Generated by Django 4.2.3 on 2023-07-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_hoody_description_hoody_name_hoody_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=1000, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='color',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='material',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hoody',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='material',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sweatshirt',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='material',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('size', models.CharField(default=None, max_length=10, null=True)),
                ('color', models.CharField(default=None, max_length=20, null=True)),
                ('material', models.CharField(default=None, max_length=20, null=True)),
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Одежда',
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='hoody',
            name='clothes_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes'),
        ),
        migrations.AddField(
            model_name='sweatshirt',
            name='clothes_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='clothes_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes'),
        ),
    ]
