# Generated by Django 4.2.3 on 2023-07-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_remove_hoody_color_remove_hoody_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoody',
            name='clothes_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes'),
        ),
    ]
