# Generated by Django 4.2.3 on 2023-07-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_hoody_clothes_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweatshirt',
            name='clothes_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='clothes_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes'),
        ),
    ]
