# Generated by Django 4.2.3 on 2023-07-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='polymorphic_ctype',
        ),
    ]
