# Generated by Django 4.2.3 on 2023-08-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
